// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLbVLnCQjsQ3ABVlUS4GlBQGWAXfaDI_g',
    appId: '1:239460398195:web:c79a34896c6194f9e26606',
    messagingSenderId: '239460398195',
    projectId: 'flutter-project-75dda',
    authDomain: 'flutter-project-75dda.firebaseapp.com',
    storageBucket: 'flutter-project-75dda.firebasestorage.app',
    measurementId: 'G-NWDQ6JDP23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBish4P6VU37Ve0-gNXrFow4Cz-Q5A7ymY',
    appId: '1:239460398195:android:4dfb1d2c032c678ee26606',
    messagingSenderId: '239460398195',
    projectId: 'flutter-project-75dda',
    storageBucket: 'flutter-project-75dda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzyIpmmMSQRNXHg5kez_OiGlSJLPcTuew',
    appId: '1:239460398195:ios:8de00edf51c7069ee26606',
    messagingSenderId: '239460398195',
    projectId: 'flutter-project-75dda',
    storageBucket: 'flutter-project-75dda.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzyIpmmMSQRNXHg5kez_OiGlSJLPcTuew',
    appId: '1:239460398195:ios:8de00edf51c7069ee26606',
    messagingSenderId: '239460398195',
    projectId: 'flutter-project-75dda',
    storageBucket: 'flutter-project-75dda.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLbVLnCQjsQ3ABVlUS4GlBQGWAXfaDI_g',
    appId: '1:239460398195:web:b7872425f537fb58e26606',
    messagingSenderId: '239460398195',
    projectId: 'flutter-project-75dda',
    authDomain: 'flutter-project-75dda.firebaseapp.com',
    storageBucket: 'flutter-project-75dda.firebasestorage.app',
    measurementId: 'G-PR5K204JLR',
  );

}